openapi: 3.1.0
info:
  title: Image to WebP API
  version: "1.0"
servers:
  - url: /

paths:
  /convert-to-webp:
    post:
      tags:
        - api
      description: Uploads an image file and returns the converted WebP file.
      consumes:
        - multipart/form-data
      produces:
        - multipart/form-data
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        "200":
          description: The converted WebP file.
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  webp:
                    type: string
                    format: binary
